// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXjd5xuqKHH8Sth8TWVIl9uO9FNaBn_mQ',
    appId: '1:223380536583:web:9fb1bad351e40a073019a2',
    messagingSenderId: '223380536583',
    projectId: 'social-kakao-app',
    authDomain: 'social-kakao-app.firebaseapp.com',
    storageBucket: 'social-kakao-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbHGFhfaDj_pm1TIuNdhVz4U9ID1F3u70',
    appId: '1:223380536583:android:afdb0ae588ce6dd93019a2',
    messagingSenderId: '223380536583',
    projectId: 'social-kakao-app',
    storageBucket: 'social-kakao-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4gtyZ2fqZfYGCULSNaOUjskH-4sXPTes',
    appId: '1:223380536583:ios:b97992790b532c6f3019a2',
    messagingSenderId: '223380536583',
    projectId: 'social-kakao-app',
    storageBucket: 'social-kakao-app.appspot.com',
    iosBundleId: 'com.example.socialKakaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4gtyZ2fqZfYGCULSNaOUjskH-4sXPTes',
    appId: '1:223380536583:ios:aa3e75603951edc43019a2',
    messagingSenderId: '223380536583',
    projectId: 'social-kakao-app',
    storageBucket: 'social-kakao-app.appspot.com',
    iosBundleId: 'com.example.socialKakaoApp.RunnerTests',
  );
}
